# Generated by Django 5.2.1 on 2025-06-11 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardian',
            name='guardian_number',
            field=models.CharField(blank=True, help_text='Auto-generated guardian number', max_length=20, null=True, unique=True),
        ),
    ]
